name: Test

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Node.js 24
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - run: pnpm test
      - run: pnpm build
